/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/tasks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Task */
    post: operations["create_task_api_tasks_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/uploads/images": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Validate Image */
    post: operations["validate_image_api_uploads_images_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/tasks/{task_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Task */
    get: operations["get_task_api_tasks__task_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/tasks/{task_id}/events": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Stream Task Events */
    get: operations["stream_task_events_api_tasks__task_id__events_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/tasks/{task_id}/evidence": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Evidence */
    get: operations["list_evidence_api_tasks__task_id__evidence_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/tasks/{task_id}/decision-pack": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Decision Pack */
    get: operations["get_decision_pack_api_tasks__task_id__decision_pack_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/tasks/{task_id}/interventions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Intervention */
    post: operations["create_intervention_api_tasks__task_id__interventions_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health Check */
    get: operations["health_check_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** Body_validate_image_api_uploads_images_post */
    Body_validate_image_api_uploads_images_post: {
      /** File */
      file: string;
    };
    /** BudgetUsage */
    BudgetUsage: {
      /** Estimated Sources */
      estimated_sources: number;
      /** Estimated Tokens */
      estimated_tokens: number;
      /** Estimated Cost Usd */
      estimated_cost_usd: number;
      /** Within Budget */
      within_budget: boolean;
    };
    /** Claim */
    Claim: {
      /** Id */
      id?: string;
      /** Statement */
      statement: string;
      dimension: components["schemas"]["EvidenceDimension"];
      /** Competitor */
      competitor: string;
      /** Evidence Ids */
      evidence_ids: string[];
      /** Confidence */
      confidence: number;
      /** Conflict Ids */
      conflict_ids?: string[];
    };
    /** Conflict */
    Conflict: {
      /** Id */
      id?: string;
      /** Claim Ids */
      claim_ids: string[];
      /** Resolution */
      resolution: string;
      /** Rationale */
      rationale: string;
      /** Confidence */
      confidence: number;
    };
    /** CoverageGateResult */
    CoverageGateResult: {
      /** Passed */
      passed: boolean;
      /** Score */
      score: number;
      /** Covered Dimensions */
      covered_dimensions: components["schemas"]["EvidenceDimension"][];
      /** Missing Dimensions */
      missing_dimensions: components["schemas"]["EvidenceDimension"][];
      /** Gap Queries */
      gap_queries: string[];
    };
    /** DecisionAction */
    DecisionAction: {
      /** Title */
      title: string;
      dimension: components["schemas"]["EvidenceDimension"];
      /** Recommendation */
      recommendation: string;
      /** Rationale */
      rationale: string;
      /** Evidence Ids */
      evidence_ids: string[];
      /**
       * Priority
       * @enum {string}
       */
      priority: "P0" | "P1" | "P2";
    };
    /** DecisionPack */
    DecisionPack: {
      /** Id */
      id?: string;
      /** Positioning */
      positioning: components["schemas"]["DecisionAction"][];
      /** Mvp Priorities */
      mvp_priorities: components["schemas"]["DecisionAction"][];
      /** Pricing Insights */
      pricing_insights?: components["schemas"]["DecisionAction"][];
      /** Battlecard */
      battlecard?: components["schemas"]["DecisionAction"][];
      /** Summary */
      summary: string;
      /**
       * Generated At
       * Format: date-time
       */
      generated_at?: string;
      /** Version */
      version?: number;
      /** Parent Pack Id */
      parent_pack_id?: string | null;
      /** Superseded By */
      superseded_by?: string | null;
      /** Status */
      status?: "draft" | "approved" | "rejected" | "superseded";
      /** Source Refs */
      source_refs?: string[];
    };
    /** Evidence */
    Evidence: {
      /** Id */
      id?: string;
      source_type: components["schemas"]["SourceType"];
      /** Source Url */
      source_url?: string | null;
      /** Competitor */
      competitor: string;
      dimension: components["schemas"]["EvidenceDimension"];
      /** Claim */
      claim: string;
      /** Quote */
      quote: string;
      /** Confidence */
      confidence: number;
      /** Freshness */
      freshness: string;
      /** Media Ref */
      media_ref?: string | null;
      /**
       * Untrusted
       * @default true
       */
      untrusted: boolean;
      /** Content Hash */
      content_hash: string;
      /**
       * License Risk
       * @default medium
       * @enum {string}
       */
      license_risk: "low" | "medium" | "high";
    };
    /**
     * EvidenceDimension
     * @enum {string}
     */
    EvidenceDimension:
      | "feature"
      | "pricing"
      | "positioning"
      | "user_feedback"
      | "risk";
    /**
     * AnalysisStrategy
     * @enum {string}
     */
    AnalysisStrategy: "cost_leadership" | "performance" | "hybrid" | "custom";
    /** AnalysisProfile */
    AnalysisProfile: {
      /** @default hybrid */
      strategy?: components["schemas"]["AnalysisStrategy"];
      /** Dimension Weights */
      dimension_weights?: {
        feature?: number;
        pricing?: number;
        user_feedback?: number;
        positioning?: number;
        risk?: number;
      };
      /** Focus Attributes */
      focus_attributes?: string[];
      /** Our Product Hints */
      our_product_hints?: string | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** InterventionRequest */
    InterventionRequest: {
      /**
       * Target
       * @enum {string}
       */
      target: "task" | "evidence" | "decision";
      /** Target Id */
      target_id: string;
      /**
       * Action
       * @enum {string}
       */
      action: "approve" | "reject" | "revise" | "force_rerun";
      /** Reason */
      reason: string;
    };
    /** ReviewScore */
    ReviewScore: {
      /** Score */
      score: number;
      /** Citation Precision */
      citation_precision: number;
      /** Claim Support Rate */
      claim_support_rate: number;
      /**
       * Hallucination Risk
       * @enum {string}
       */
      hallucination_risk: "low" | "medium" | "high";
      /** Notes */
      notes: string[];
    };
    /**
     * SourceType
     * @enum {string}
     */
    SourceType: "url" | "text" | "image" | "video" | "document";
    /** TaskBudget */
    TaskBudget: {
      /**
       * Max Sources
       * @default 8
       */
      max_sources: number;
      /**
       * Max Tokens
       * @default 12000
       */
      max_tokens: number;
      /**
       * Max Cost Usd
       * @default 1
       */
      max_cost_usd: number;
      /**
       * Timeout Seconds
       * @default 90
       */
      timeout_seconds: number;
    };
    /** CompetitorUrl */
    CompetitorUrl: {
      /** Competitor */
      competitor: string;
      /** Url */
      url: string;
    };
    /** TaskCreateRequest */
    TaskCreateRequest: {
      /** Product Goal */
      product_goal: string;
      /** Competitors */
      competitors: string[];
      /** Urls */
      urls?: string[];
      /** Competitor Urls */
      competitor_urls?: components["schemas"]["CompetitorUrl"][];
      /** Comments */
      comments?: string | null;
      /** Image Names */
      image_names?: string[];
      budget?: components["schemas"]["TaskBudget"];
      /** Analysis Profile */
      analysis_profile?: components["schemas"]["AnalysisProfile"];
    };
    /** TaskEvent */
    TaskEvent: {
      /** Id */
      id?: string;
      /** Task Id */
      task_id: string;
      /** Stage */
      stage: string;
      /** Message */
      message: string;
      status: components["schemas"]["TaskStatus"];
      /**
       * Created At
       * Format: date-time
       */
      created_at?: string;
    };
    /** TaskRecord */
    TaskRecord: {
      /** Id */
      id?: string;
      request: components["schemas"]["TaskCreateRequest"];
      /** @default queued */
      status: components["schemas"]["TaskStatus"];
      /** Evidence */
      evidence?: components["schemas"]["Evidence"][];
      /** Claims */
      claims?: components["schemas"]["Claim"][];
      /** Conflicts */
      conflicts?: components["schemas"]["Conflict"][];
      coverage?: components["schemas"]["CoverageGateResult"] | null;
      decision_pack?: components["schemas"]["DecisionPack"] | null;
      review?: components["schemas"]["ReviewScore"] | null;
      budget_usage?: components["schemas"]["BudgetUsage"] | null;
      /** Events */
      events?: components["schemas"]["TaskEvent"][];
      metrics?: components["schemas"]["TaskMetrics"] | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at?: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at?: string;
    };
    /** TaskMetrics */
    TaskMetrics: {
      /** Total Duration Ms */
      total_duration_ms: number;
      /** Stage Durations */
      stage_durations: Record<string, number>;
      /** Evidence Count */
      evidence_count: number;
      /** Conflict Count */
      conflict_count: number;
      /** Intervention Count */
      intervention_count: number;
    };
    /**
     * TaskStatus
     * @enum {string}
     */
    TaskStatus: "queued" | "running" | "completed" | "cancelled" | "failed";
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  create_task_api_tasks_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TaskCreateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TaskRecord"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  validate_image_api_uploads_images_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_validate_image_api_uploads_images_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_task_api_tasks__task_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        task_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TaskRecord"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  stream_task_events_api_tasks__task_id__events_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        task_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_evidence_api_tasks__task_id__evidence_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        task_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_decision_pack_api_tasks__task_id__decision_pack_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        task_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_intervention_api_tasks__task_id__interventions_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        task_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["InterventionRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  health_check_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
}
